import NAVIGATION_LINKS from "./NAVIGATION_LINKS";
import DETAILS_DATA from "./DETAILS_DATA";
import OPTIONS from "./OPTIONS";
import BUILDERS_DATA from "./BUILDERS_DATA";
import RELATED_DEALS from "./RELATED_DEALS";

export {
  NAVIGATION_LINKS,
  DETAILS_DATA,
  OPTIONS,
  BUILDERS_DATA,
  RELATED_DEALS,
};
